version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: bloomberg_fx
    ports:
      - "3303:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mysql-spring-boot

  app:
    build: 
      context: .
      dockerfile: DockerFile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/bloomberg_fx
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db
    networks:
      - mysql-spring-boot
    restart: on-failure
volumes:
  mysql-data:
networks:
  mysql-spring-boot:
    driver: bridge
    